# Generated by Django 4.2.9 on 2024-02-12 21:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_chat_is_private_alter_chat_chat_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmassages',
            name='type',
            field=models.CharField(default='users'),
        ),

    ]
