# Generated by Django 4.2.9 on 2024-02-04 13:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_roomtype'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='type',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='chat.roomtype'),
        ),
    ]
