# Generated by Django 4.2.9 on 2024-02-04 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_chatroom_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='uniqe_key',
            field=models.CharField(default=2, max_length=100, unique=True),
        ),
    ]
