# Generated by Django 4.2.9 on 2024-02-04 14:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0005_chatroom_uniqe_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='room_user',
            field=models.ManyToManyField(blank=True, related_name='room_users', to=settings.AUTH_USER_MODEL),
        ),
    ]
