# Generated by Django 4.2.9 on 2024-02-04 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_chatroom_room_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatroom',
            name='uniqe_key',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
