# Generated by Django 4.2.9 on 2024-02-15 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_chat_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatusers',
            name='status',
            field=models.CharField(default='active', max_length=20),
        ),
    ]
