# Generated by Django 4.2.9 on 2024-02-09 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(blank=True, default='users/2024/02/09/images.png', upload_to='users/%Y/%m/%d'),
        ),
    ]
